name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
use std::collections::HashMap;
use std::io::Read;
use std::str::FromStr;

struct Todo {
    // use rust built in HashMap to store key - val pairs
    map: HashMap<String, bool>,
}
impl Todo {
    fn new() -> Result<Todo, std::io::Error> {
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .read(true)
            .open("db.txt")?;
        let mut content = String::new();
        f.read_to_string(&mut content)?;
        let map: HashMap<String, bool> = content
            .lines()
            .map(|line| line.splitn(2, '\t').collect::<Vec<&str>>())
            .map(|v| (v[0], v[1]))
            .map(|(k, v)| (String::from(k), bool::from_str(v).unwrap()))
            .collect();
        Ok(Todo { map })
    }

    fn insert(&mut self, key: &String) {
        // insert a new item into our map.
        // we pass true as value
        self.map.insert(key.clone(), true);
    }

    fn save(&self) -> Result<(), std::io::Error> {
        let mut content = String::new();
        for (k, v) in &self.map {
            let record = format!("{}\t{}\n", k, v);
            content.push_str(&record);
        }
        std::fs::write("db.txt", content)
    }

    fn complete(&mut self, key: &String) -> Option<()> {
        match self.map.get_mut(key) {
            Some(v) => Some(*v = false),
            None => None,
        }
    }
}

fn do_something(s: String) {
    // now do_something is the owner of s.
    // Rust will free the memory associated with s 
    // as soon as it goes out of this function scope.
    println!("Received: {}", s);
}

fn main() {
    // the owner of the String is x
    let x = String::from("Hello");

    // we move the value inside this function.
    do_something(x);

    // The compiler will throw an error if we tried to use x here
    // because we moved it inside "do_something"
    // we cannot use it as we don't have ownership
    // and the value has been dropped.
    // println!("{}", x);  // This would cause a compile error!

    let _action = std::env::args().nth(1).expect("Please specify an action");
    let _item = std::env::args().nth(2).expect("Please specify an item");
    let mut todo = Todo::new().expect("Initialisation of db failed");

    println!("{:?}, {:?}", _action, _item);
    if _action == "add" {
        todo.insert(&_item);
        match todo.save() {
            Ok(_) => println!("todo saved"),
            Err(why) => println!("An error occurred: {}", why),
        }
    } else if _action == "complete" {
        match todo.complete(&_item) {
            None => println!("'{}' is not present in the list", _item),
            Some(_) => match todo.save() {
                Ok(_) => println!("todo saved"),
                Err(why) => println!("An error occurred: {}", why),
            },
        }
    }
}
